# Generated by Django 4.2.3 on 2023-08-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='collegename',
            new_name='college',
        ),
    ]
